// Code generated by goctl. DO NOT EDIT.
package types

type MerchantUser struct {
	ID            int64  `json:"id"`
	Merchant_code string `json:"merchantCode"`
	Account       string `json:"account"`
	Status        string `json:"status"`
	DisableDelete string `json:"disableDelete"`
	RegisteredAt  string `json:"registeredAt"`
	LastLogin_at  string `json:"lastLoginAt"`
	RoleNames     string `json:"roleNames"`
}

type MerchantUserQueryAllRequest struct {
	MerchantCode string `json:"merchantCode,optional"`
	Account      string `json:"account,optional"`
	RoleId       int64  `json:"roleId,optional"`
	Status       string `json:"status,optional"`
	PageNum      int    `json:"pageNum,optional" gorm:"-"`
	PageSize     int    `json:"pageSize,optional" gorm:"-"`
}

type MerchantUserQueryAllResponse struct {
	List     []MerchantUser `json:"list"`
	PageNum  int            `json:"pageNum"`
	PageSize int            `json:"pageSize"`
	RowCount int64          `json:"rowCount"`
}

type MerchantUserResetPasswordRequest struct {
	ID int64 `json:"id"`
}

type MerchantUserUpdatePasswordRequest struct {
	ID              int64  `json:"id"`
	OldPassword     string `json:"oldPassword,optional" validate:"required" gorm:"-"`
	Password        string `json:"password" validate:"required,alphanumLength=8/16"`
	PasswordConfirm string `json:"passwordConfirm" validate:"eqfield=Password" gorm:"-"`
}

type Timezonex struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type TimezonexCreateRequest struct {
	Code string `json:"code" validate: "required, lte=2"`
	Name string `json:"name" validate: "required, lte=64"`
}

type TimezonexUpdateRequest struct {
	ID   int64  `json:"id"`
	Code string `json:"code" validate: "required, lte=2"`
	Name string `json:"name" validate: "required, lte=64"`
}

type TimezonexDeleteRequest struct {
	ID int64 `json:"id"`
}

type TimezonexQueryRequest struct {
	ID int64 `json:"id"`
}

type TimezonexQueryResponse struct {
	Timezonex
}

type TimezonexQueryAllRequest struct {
	Code     string `json:"code, optional"`
	Name     string `json:"name, optional"`
	PageNum  int    `json:"pageNum" gorm:"-"`
	PageSize int    `json:"pageSize" gorm:"-"`
}

type TimezonexQueryAllResponse struct {
	List     []Timezonex `json:"list"`
	PageNum  int         `json:"pageNum"`
	PageSize int         `json:"pageSize"`
	RowCount int64       `json:"rowCount"`
}

type Currency struct {
	ID   int64  `json:"id, optional"`
	Code string `json:"code, optional"`
	Name string `json:"name, optional"`
}

type CurrencyCreateRequest struct {
	Code string `json:"code" valiate:"required,lte=4"`
	Name string `json:"name" valiate:"required,lte=16"`
}

type CurrencyUpdateRequest struct {
	ID   int64  `json:"id"`
	Code string `json:"code" valiate:"required,lte=4"`
	Name string `json:"name" valiate:"required,lte=16"`
}

type CurrencyDeleteRequest struct {
	ID int64 `json:"id"`
}

type CurrencyQueryRequest struct {
	ID int64 `json:"id"`
}

type CurrencyQueryResponse struct {
	Currency
}

type CurrencyQueryAllRequest struct {
	Code     string `json:"code, optional"`
	Name     string `json:"name, optional"`
	PageNum  int    `json:"pageNum, optional" gorm:"-"`
	PageSize int    `json:"pageSize, optional" gorm:"-"`
}

type CurrencyQueryAllResponse struct {
	List     []Currency `json:"list"`
	PageNum  int        `json:"pageNum"`
	PageSize int        `json:"pageSize"`
	RowCount int64      `json:"rowCount"`
}

type LanguageCreateRequest struct {
	Code string `json:"code" valiate:"required,lte=2"`
	Name string `json:"name" valiate:"required,lte=16"`
}

type LanguageUpdateRequest struct {
	ID   string `json:"id"`
	Code string `json:"code" valiate:"required,lte=2"`
	Name string `json:"name" valiate:"required,lte=16"`
}

type LanguageQueryRequest struct {
	ID int64 `json:"id"`
}

type LanguageDeleteRequest struct {
	ID int64 `json:"id"`
}

type Language struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type LanguageQueryResponse struct {
	Language
}

type LanguageQueryAllRequest struct {
	Code     string `json:"code ,optional"`
	Name     string `json:"name,optional"`
	PageNum  int    `json:"pageNum" gorm:"-"` //gorm:"-" 忽略這參數檢查是否有給
	PageSize int    `json:"pageSize" gorm:"-"`
}

type LanguageQueryAllResponse struct {
	List     []Language `json:"list"`
	PageNum  int        `json:"pageNum"`
	PageSize int        `json:"pageSize"`
	RowCount int64      `json:"rowCount"`
}

type BankBlockAccount struct {
	ID          int64  `json:"id"`
	BankAccount string `json:"bankAccount"`
	BankNo      string `json:"bankNo"`
	Memo        string `json:"memo"`
	CreatedAt   string `json:"createdAt"`
	Name        string `json:"name"`
}

type BankBlockAccountCreateRequest struct {
	BankAccount string `json:"bankAccount" validate: "required"`
	Name        string `json:"name" validate: "required"`
	Memo        string `json:"memo"`
}

type BankBlockAccountUpdateRequest struct {
	ID          int64  `json:"id"`
	BankAccount string `json:"bankAccount" validate: "required"`
	Name        string `json:"name" validate: "required"`
	Memo        string `json:"memo"`
}

type BankBlockAccountDeleteRequest struct {
	ID int64 `json:"id"`
}

type BankBlockAccountQueryRequest struct {
	ID int64 `json:"id"`
}

type BankBlockAccountQueryResponse struct {
	BankBlockAccount
}

type BankBlockAccountQueryAllRequest struct {
	BankAccount string `json:"bankAccount, optional"`
	Name        string `json:"name, optional"`
	StartAt     string `json:"startAt, optional"`
	EndAt       string `json:"endAt, optional"`
	PageNum     int    `json:"pageNum" gorm:"-"`
	PageSize    int    `json:"pageSize" gorm:"-"`
}

type BankBlockAccountQueryAllResponse struct {
	List     []BankBlockAccount `json:"list"`
	PageNum  int                `json:"pageNum"`
	PageSize int                `json:"pageSize"`
	RowCount int64              `json:"rowCount"`
}

type Bank struct {
	ID           int64         `json:"id"`
	BankNo       string        `json:"bankNo"`
	BankName     string        `json:"bankName"`
	BankNameEn   string        `json:"bankNameEn"`
	Abbr         string        `json:"abbr"`
	BranchNo     string        `json:"branchNo"`
	BranchName   string        `json:"branchName"`
	City         string        `json:"city"`
	Province     string        `json:"province"`
	CurrencyCode string        `json:"currencyCode"`
	Status       string        `json:"status"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_banks:foreignKey:bankNo;joinForeignKey:bank_no;references:code;joinReferences:channel_code"`
}

type BankCreateRequest struct {
	BankNo       string        `json:"bankNo, optional"`
	BankName     string        `json:"bankName, valiate: "required""`
	BankNameEn   string        `json:"bankNameEn" valiate: "required"`
	Abbr         string        `json:"abbr" valiate: "required"`
	BranchNo     string        `json:"branchNo, optional "`
	BranchName   string        `json:"branchName, optional"`
	City         string        `json:"city, optional"`
	Province     string        `json:"province, optional"`
	CurrencyCode string        `json:"currencyCode" valiate: "required"`
	Status       string        `json:"status" valiate: "required"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_banks:foreignKey:bankNo;joinForeignKey:bank_no;references:code;joinReferences:channel_code"`
}

type BankUpdateRequest struct {
	ID           int64         `json:"id, optional"`
	BankNo       string        `json:"bankNo" valiate: "required"`
	BankName     string        `json:"bankName, optional"`
	BankNameEn   string        `json:"bankNameEn, optional"`
	Abbr         string        `json:"abbr, optional"`
	BranchNo     string        `json:"branchNo, optional"`
	BranchName   string        `json:"branchName, optional"`
	City         string        `json:"city, optional"`
	Province     string        `json:"province, optional"`
	CurrencyCode string        `json:"currencyCode" valiate: "required"`
	Status       string        `json:"status" valiate: "required"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_banks:foreignKey:bankNo;joinForeignKey:bank_no;references:code;joinReferences:channel_code"`
}

type BankDeleteRequest struct {
	ID int64 `json:"id"`
}

type BankQueryRequest struct {
	ID int64 `json:"id"`
}

type BankQueryResponse struct {
	Bank
}

type BankQueryAllRequest struct {
	CurrencyCode string `json:"currencyCode, optional"`
	BankNo       string `json:"bankNo, optional"`
	BankName     string `json:"bankName, optional"`
	PageNum      int    `json:"pageNum, optional" gorm:"-"`
	PageSize     int    `json:"pageSize, optional" gorm:"-"`
}

type BankQueryAllResponse struct {
	List     []Bank `json:"list"`
	PageNum  int    `json:"pageNum" gorm:"-"`
	PageSize int    `json:"pageSize" gorm:"-"`
	RowCount int64  `json:"rowCount"`
}

type Merchant struct {
	ID                  int64             `json:"id, optional"`
	Code                string            `json:"code, optional"`
	AgentLayerCode      string            `json:"agentLayerCode, optional"`
	AgentParentCode     string            `json:"agentParentCode, optional"`
	ScrectKey           string            `json:"-, optional"`
	AccessToken         string            `json:"-, optional"`
	Status              string            `json:"status, optional"`
	AgentStatus         string            `json:"agentStatus, optional"`
	Contact             MerchantContact   `json:"contact, optional"`
	BizInfo             MerchantBizInfo   `json:"bizInfo, optional"`
	BoIP                string            `json:"boIp, optional"`
	ApiIP               string            `json:"apiIp, optional"`
	IsWithdraw          string            `json:"isWithdraw, optional"`
	WithdrawPassword    string            `json:"-, optional"`
	LoginValidatedType  string            `json:"loginValidatedType, optional"`
	PayingValidatedType string            `json:"payingValidatedType, optional"`
	ApiCodeType         string            `json:"apiCodeType, optional"`
	BillLadingType      string            `json:"billLadingType, optional"`
	Lang                string            `json:"lang, optional"`
	RegisteredAt        int64             `json:"registeredAt, optional"`
	RegisteredAtS       string            `json:"registeredAtS, optional" gorm:"-"`
	MerchantBalances    []MerchantBalance `json:"merchantBalances, optional" gorm:"foreignKey:MerchantCode;references:Code"`
	//Users               []User             `json:"users, optional, optional" gorm:"many2many:au_user_merchants;foreignKey:code;joinForeignKey:merchant_code;references:account;joinReferences:user_account;"`
	MerchantCurrencies []MerchantCurrency `json:"merchantCurrencies, optional" gorm:"foreignKey:MerchantCode;references:Code"`
}

type MerchantContact struct {
	Phone                 string `json:"phone, optional"`
	Email                 string `json:"email, optional"`
	CommunicationSoftware string `json:"communicationSoftware, optional"`
	CommunicationNickname string `json:"communicationNickname, optional"`
	GroupName             string `json:"groupName, optional"`
	GroupID               string `json:"groupId, optional"`
}

type MerchantBizInfo struct {
	CompanyName      string `json:"companyName, optional"`
	OperatingWebsite string `json:"operatingWebsite, optional"`
	TestAccount      string `json:"testAccount, optional"`
	TestPassword     string `json:"testPassword, optional"`
	Remark           string `json:"remark, optional"`
}

type MerchantDeleteRequest struct {
	ID int64 `json:"id"`
}

type MerchantQueryRequest struct {
	ID int64 `json:"id"`
}

type MerchantQueryResponse struct {
	Merchant
}

type MerchantQueryAllRequest struct {
	Code           string `json:"code, optional"`
	AgentLayerCode string `json:"agentLayerCode, optional"`
	PageNum        int    `json:"pageNum, optional" gorm:"-"`
	PageSize       int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantQueryAllResponse struct {
	List     []Merchant `json:"list"`
	PageNum  int        `json:"pageNum"`
	PageSize int        `json:"pageSize"`
	RowCount int64      `json:"rowCount"`
}

type MerchantListView struct {
	ID                  int64   `json:"id, optional"`
	Code                string  `json:"code, optional"`
	AgentLayerCode      string  `json:"agentLayerCode, optional"`
	Status              string  `json:"status, optional"`
	CreatedAt           string  `json:"createdAt, optional"`
	AgentStatus         string  `json:"agentStatus, optional"`
	CurrencyCode        string  `json:"currencyCode, optional" validate:"required"`
	XfBalance           float64 `json:"xfBalance, optional"`
	DfBalance           float64 `json:"dfBalance, optional"`
	FrozenAmount        float64 `json:"frozenAmount, optional"`
	Commission          float64 `json:"commission, optional"`
	WithdrawHandlingFee float64 `json:"withdrawHandlingFee, optional"`
	MinWithdrawCharge   float64 `json:"minWithdrawCharge"`
	MaxWithdrawCharge   float64 `json:"maxWithdrawCharge"`
}

type MerchantQueryListViewRequest struct {
	Code                     string   `json:"code, optional"`
	AgentLayerCode           string   `json:"agentLayerCode, optional"`
	BalanceCurrencyCode      string   `json:"balanceCurrencyCode, optional"`
	Currencies               []string `json:"currencies, optional"`
	UserID                   int64    `json:"userId, optional"`
	MerchantCurrenciesStatus string   `json:"merchantCurrenciesStatus, optional"`
	PageNum                  int      `json:"pageNum, optional" gorm:"-"`
	PageSize                 int      `json:"pageSize, optional" gorm:"-"`
}

type MerchantQueryListViewResponse struct {
	List     []MerchantListView `json:"list"`
	PageNum  int                `json:"pageNum"`
	PageSize int                `json:"pageSize"`
	RowCount int64              `json:"rowCount"`
}

type MerchantQueryDistinctCode struct {
	CurrencyCode string `json:"currencyCode, optional"`
	Status       string `json:"status, optional"`
}

type MerchantUpdateStatusRequest struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

type MerchantUpdateAgentStatusRequest struct {
	ID          int64  `json:"id"`
	AgentStatus string `json:"agentStatus"`
}

type MerchantUpdateBillLadingTypeRequest struct {
	ID             int64  `json:"id"`
	BillLadingType string `json:"billLadingType"`
}

type MerchantResetPasswordRequest struct {
	Name string `json:"name"`
}

type MerchantResetScrectKeyRequest struct {
	ID int64 `json:"id"`
}

type MerchantGetScrectKeyRequest struct {
	ID int64 `json:"id"`
}

type MerchantGetScrectKeyResponse struct {
	ScrectKey string `json:"screctKey"`
}

type MerchantTransferParentAgentRequest struct {
	Code            string `json:"code"`
	AgentParentCode string `json:"agentParentCode"`
}

type UpdateWithdrawPasswordRequest struct {
	ID               int64  `json:"id"`
	WithdrawPassword string `json:"withdrawPassword" validate:"required,alphanumLength=8/16"`
}

type ResetWithdrawPasswordRequest struct {
	ID int64 `json:"id"`
}

type MerchantBalance struct {
	ID           int64   `json:"id, optional"`
	MerchantCode string  `json:"merchantCode, optional"`
	CurrencyCode string  `json:"currencyCode, optional"`
	BalanceType  string  `json:"balanceType, optional"  validate:"required"`
	Balance      float64 `json:"balance"`
	FrozenAmount float64 `json:"frozenAmount, optional"`
}

type MerchantPtBalance struct {
	ID           int64   `json:"id, optional"`
	MerchantCode string  `json:"merchantCode, optional"`
	CurrencyCode string  `json:"currencyCode, optional"`
	ChannelCode  string  `json:"channelCode, optional"`
	PayTypeCode  string  `json:"payTypeCode, optional"`
	Name         string  `json:"name, optional"`
	Balance      float64 `json:"balance"`
}

type MerchantBalanceCreateRequest struct {
	ID           int64   `json:"id, optional"`
	MerchantCode string  `json:"merchantCode, optional" validate:"required"`
	CurrencyCode string  `json:"currencyCode, optional" validate:"required"`
	BalanceType  string  `json:"balanceType, optional"  validate:"required"`
	Balance      float64 `json:"balance"`
	FrozenAmount float64 `json:"frozenAmount, optional"`
	Commission   float64 `json:"commission, optional"`
}

type MerchantBalanceUpdateRequest struct {
	MerchantCode string  `json:"merchantCode"`
	CurrencyCode string  `json:"currencyCode"`
	BalanceType  string  `json:"balanceType"`
	Comment      string  `json:"comment"`
	Amount       float64 `json:"amount"`
}

type MerchantBalanceDeleteRequest struct {
	ID int64 `json:"id"`
}

type MerchantBalanceQueryRequest struct {
	ID int64 `json:"id"`
}

type MerchantBalanceQueryResponse struct {
	MerchantBalance
}

type MerchantBalanceQueryAllRequest struct {
	MerchantCode string `json:"merchantCode, optional"`
	CurrencyCode string `json:"currencyCode, optional"`
	PageNum      int    `json:"pageNum, optional" gorm:"-"`
	PageSize     int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantBalanceQueryAllResponse struct {
	List     []MerchantBalance `json:"list"`
	PageNum  int               `json:"pageNum"`
	PageSize int               `json:"pageSize"`
	RowCount int64             `json:"rowCount"`
}

type MerchantChannelRate struct {
	ID                  int64   `json:"id"`
	MerchantCode        string  `json:"merchantCode"`
	ChannelPayTypesCode string  `json:"channelPayTypesCode"`
	ChannelCode         string  `json:"channelCode"`
	PayTypeCode         string  `json:"payTypeCode"`
	PayTypeCodeNum      string  `json:"payTypeCodeNum"`
	Designation         string  `json:"designation"`
	DesignationNo       string  `json:"designationNo, optional"`
	Fee                 float64 `json:"fee"`
	HandlingFee         float64 `json:"handlingFee"`
	Status              string  `json:"status"`
	MerchantPtBalanceId int64   `json:"merchantPtBalanceId"`
}

type MerchantChannelRateConfigureRequest struct {
	ID                  int64   `json:"id, optional"`
	MerchantCode        string  `json:"merchantCode"`
	ChannelPayTypesCode string  `json:"channelPayTypesCode"`
	ChannelCode         string  `json:"channelCode"`
	PayTypeCode         string  `json:"payTypeCode"`
	PayTypeCodeNum      string  `json:"payTypeCodeNum"`
	Designation         string  `json:"designation"`
	DesignationNo       string  `json:"designationNo, optional"`
	Fee                 float64 `json:"fee"`
	HandlingFee         float64 `json:"handlingFee"`
	Status              string  `json:"status, optional"`
}

type MerchantConfigureRate struct {
	IsConfigure                 bool    `json:"isConfigure"`
	ChnName                     string  `json:"chnName"`
	ChnCode                     string  `json:"chnCode"`
	ChnIsNzPre                  string  `json:"chnIsNzPre"`
	ChnIsProxy                  string  `json:"chnIsProxy"`
	ChnStatus                   string  `json:"chnStatus"`
	CurrencyCode                string  `json:"currencyCode"`
	PayTypeCode                 string  `json:"payTypeCode"`
	ChnPayTypeCode              string  `json:"chnPayTypeCode"`
	ChnPayTypePayTypeCodeNum    string  `json:"chnPayTypePayTypeCodeNum"`
	PayTypeFee                  float64 `json:"payTypeFee"`
	PayTypeHandlingFee          float64 `json:"payTypeHandlingFee"`
	ChnPayTypeMaxInternalCharge float64 `json:"chnPayTypeMaxInternalCharge"`
	ChnPayTypeDailyTxLimit      float64 `json:"chnPayTypeDailyTxLimit"`
	ChnPayTypeSingleMinCharge   float64 `json:"chnPayTypeSingleMinCharge"`
	ChnPayTypeSingleMaxCharge   float64 `json:"chnPayTypeSingleMaxCharge"`
	ChnPayTypeBillDate          int     `json:"chnPayTypeBillDate"`
	ChnPayTypeStatus            string  `json:"chnPayTypeStatus"`
	MerCode                     string  `json:"merCode"`
	MerBillLadingType           string  `json:"merBillLadingType"`
	MerStatus                   string  `json:"merStatus"`
	MerChnRateId                int64   `json:"merChnRateId"`
	MerChnRateFee               float64 `json:"merChnRateFee"`
	MerChnRateHandlingFee       float64 `json:"merChnRateHandlingFee"`
	MerChnRateDesignation       string  `json:"merChnRateDesignation"`
	MerChnRateDesignationNo     string  `json:"merChnRateDesignationNo"`
	MerChnRateStatus            string  `json:"merChnRateStatus"`
	ParentMerCode               string  `json:"parentMerCode"`
	ParentMerChnRateStatus      string  `json:"parentMerChnRateStatus"`
}

type MerchantConfigureRateListRequest struct {
	CurrencyCode string `json:"currencyCode"`
	MerchantCode string `json:"merchantCode"`
	PayTypeCode  string `json:"payTypeCode"`
	PageNum      int    `json:"pageNum, optional" gorm:"-"`
	PageSize     int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantConfigureRateListResponse struct {
	List []MerchantConfigureRate `json:"list"`
}

type MerchantRateListView struct {
	ChnName                     string  `json:"chnName"`
	ChnCode                     string  `json:"chnCode"`
	CurrencyCode                string  `json:"currencyCode"`
	CurrencyName                string  `json:"currencyName"`
	ChnStatus                   string  `json:"chnStatus"`
	PayTypeCode                 string  `json:"payTypeCode"`
	PayTypeName                 string  `json:"payTypeName"`
	ChnPayTypeCode              string  `json:"chnPayTypeCode"`
	ChnPayTypeFee               float64 `json:"chnPayTypeFee"`
	ChnPayTypeHandlingFee       float64 `json:"chnPayTypeHandlingFee"`
	ChnPayTypeMaxInternalCharge float64 `json:"chnPayTypeMaxInternalCharge"`
	ChnPayTypeDailyTxLimit      float64 `json:"chnPayTypeDailyTxLimit"`
	ChnPayTypeSingleMinCharge   float64 `json:"chnPayTypeSingleMinCharge"`
	ChnPayTypeSingleMaxCharge   float64 `json:"chnPayTypeSingleMaxCharge"`
	ChnPayTypeBillDate          int     `json:"chnPayTypeBillDate"`
	ChnPayTypeStatus            string  `json:"chnPayTypeStatus"`
	MerCode                     string  `json:"merCode"`
	MerStatus                   string  `json:"merStatus"`
	MerChnRateFee               float64 `json:"merChnRateFee"`
	MerChnRateHandlingFee       float64 `json:"merChnRateHandlingFee"`
	MerChnRateDesignation       string  `json:"merChnRateDesignation"`
	MerChnRateStatus            string  `json:"merChnRateStatus"`
	ParentMerCode               string  `json:"parentMerCode"`
	ParentMerChnRateFee         float64 `json:"parentMerChnRateFee"`
	ParentMerChnRateHandlingFee float64 `json:"parentMerChnRateHandlingFee"`
	ParentMerChnRateStatus      string  `json:"parentMerChnRateStatus"`
}

type MerchantOrderRateListView struct {
	ChannelPayTypesCode string  `json:"channelPayTypesCode"`
	PayTypeCode         string  `json:"payTypeCode"`
	PayTypeCodeNum      string  `json:"payTypeCodeNum"`
	MerHandlingFee      float64 `json:"merHandlingFee"`
	MerFee              float64 `json:"merFee"`
	Designation         string  `json:"designation"`
	DesignationNo       string  `json:"designationNo"`
	ChannelCode         string  `json:"channelCode"`
	CurrencyCode        string  `json:"currencyCode"`
	MaxInternalCharge   float64 `json:"maxInternalCharge"`
	SingleMinCharge     float64 `json:"singleMinCharge"`
	SingleMaxCharge     float64 `json:"singleMaxCharge"`
	MerchantCode        string  `json:"merchantCode"`
	MerchnrateStatus    string  `json:"merchnrateStatus"`
	ChnStatus           string  `json:"chnStatus"`
	ChnIsProxy          string  `json:"chnIsProxy"`
	CptStatus           string  `json:"chnpayTypeStatus"`
	CptFee              float64 `json:"cptFee"`
	CptHandlingFee      float64 `json:"cptHandlingFee"`
}

type MerchantQueryRateListViewRequest struct {
	CurrencyCode       string `json:"currencyCode, optional"`
	MerchantCode       string `json:"merchantCode, optional"`
	ParentMerchantCode string `json:"parentMerchantCode, optional"`
	PayTypeCode        string `json:"payTypeCode, optional"`
	PayTypeName        string `json:"payTypeName, optional"`
	ChannelName        string `json:"channelName, optional"`
	ChannelPayTypeCode string `json:"channelPayTypeCode, optional"`
	PageNum            int    `json:"pageNum, optional" gorm:"-"`
	PageSize           int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantQueryRateListViewResponse struct {
	List     []MerchantRateListView `json:"list"`
	PageNum  int                    `json:"pageNum, optional" gorm:"-"`
	PageSize int                    `json:"pageSize, optional" gorm:"-"`
	RowCount int64                  `json:"rowCount"`
}

type MerchantRateGetCodeDropDownListRequest struct {
	CurrencyCode string `json:"currencyCode, optional"`
}

type MerchantRateGetParentCodeDropDownListRequest struct {
	CurrencyCode string `json:"currencyCode, optional"`
}

type MerchantCurrency struct {
	ID                  int64   `json:"id, optional"`
	MerchantCode        string  `json:"merchantCode, optional"`
	CurrencyCode        string  `json:"currencyCode, optional"`
	WithdrawHandlingFee float64 `json:"withdrawHandlingFee, optional"`
	MinWithdrawCharge   float64 `json:"minWithdrawCharge, optional"`
	MaxWithdrawCharge   float64 `json:"maxWithdrawCharge, optional"`
	Status              string  `json:"status, optional"`
}

type MerchantCurrencyCreateRequest struct {
	MerchantCode        string  `json:"merchantCode, optional"`
	CurrencyCode        string  `json:"currencyCode, optional"`
	WithdrawHandlingFee float64 `json:"withdrawHandlingFee, optional"`
	MinWithdrawCharge   float64 `json:"minWithdrawCharge, optional"`
	MaxWithdrawCharge   float64 `json:"maxWithdrawCharge, optional"`
	Status              string  `json:"status, optional"`
}

type MerchantCurrencyUpdateRequest struct {
	ID                  int64   `json:"id, optional"`
	MerchantCode        string  `json:"merchantCode, optional"`
	CurrencyCode        string  `json:"currencyCode, optional"`
	WithdrawHandlingFee float64 `json:"withdrawHandlingFee, optional"`
	MinWithdrawCharge   float64 `json:"minWithdrawCharge, optional"`
	MaxWithdrawCharge   float64 `json:"maxWithdrawCharge, optional"`
	Status              string  `json:"status, optional"`
}

type MerchantCurrencyQueryRequest struct {
	ID int64 `json:"id"`
}

type MerchantCurrencyQueryResponse struct {
	MerchantCurrency
}

type MerchantCurrencyQueryAllRequest struct {
	MerchantCode string `json:"merchantCode, optional"`
	CurrencyCode string `json:"currencyCode, optional"`
	Status       string `json:"status, optional"`
	PageNum      int    `json:"pageNum, optional" gorm:"-"`
	PageSize     int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantCurrencyQueryAllResponse struct {
	List     []MerchantCurrency `json:"list"`
	PageNum  int                `json:"pageNum"`
	PageSize int                `json:"pageSize"`
	RowCount int64              `json:"rowCount"`
}

type MerchantGetAvailableCurrencyRequest struct {
	MerchantCode string `json:"merchantCode"`
}

type MerchantUpdateCurrenciesRequest struct {
	MerchantCode string `json:"merchantCode"`
}

type MerchantBindBank struct {
	ID           int64  `json:"id"`
	MerchantCode string `json:"merchantCode"`
	CurrencyCode string `json:"currencyCode"`
	Name         string `json:"name"`
	BankAccount  string `json:"bankAccount"`
	BankNo       string `json:"bankNo"`
	BankName     string `json:"bankName"`
	Province     string `json:"province"`
	City         string `json:"city"`
}

type MerchantBindBankCreateRequest struct {
	MerchantCode string `json:"merchantCode, optional"`
	CurrencyCode string `json:"currencyCode"`
	Name         string `json:"name"`
	BankAccount  string `json:"bankAccount"`
	BankNo       string `json:"bankNo"`
	BankName     string `json:"bankName"`
	Province     string `json:"province"`
	City         string `json:"city"`
}

type MerchantBindBankUpdateRequest struct {
	ID           int64  `json:"id"`
	CurrencyCode string `json:"currencyCode, optional"`
	Name         string `json:"name, optional"`
	BankAccount  string `json:"bankAccount, optional"`
	BankNo       string `json:"bankNo, optional"`
	BankName     string `json:"bankName, optional"`
	Province     string `json:"province, optional"`
	City         string `json:"city, optional"`
}

type MerchantBindBankDeleteRequest struct {
	ID int64 `json:"id"`
}

type MerchantBindBankQueryRequest struct {
	ID int64 `json:"id"`
}

type MerchantBindBankQueryResponse struct {
	MerchantBindBank
}

type MerchantBindBankQueryAllRequest struct {
	CurrencyCode string `json:"currencyCode, optional"`
	PageNum      int    `json:"pageNum" gorm:"-"`
	PageSize     int    `json:"pageSize" gorm:"-"`
}

type MerchantBindBankQueryAllResponse struct {
	List     []MerchantBindBank `json:"list"`
	PageNum  int                `json:"pageNum"`
	PageSize int                `json:"pageSize"`
	RowCount int64              `json:"rowCount"`
}

type MerchantBalanceRecord struct {
	ID                int64       `json:"id, optional"`
	MerchantBalanceId int64       `json:"merchantBalanceId"`
	MerchantCode      string      `json:"merchantCode, optional"`
	CurrencyCode      string      `json:"currencyCode, optional"`
	OrderNo           string      `json:"orderNo"`
	MerchantOrderNo   string      `json:"merchantOrderNo"`
	OrderType         string      `json:"orderType"`
	ChannelCode       string      `json:"channelCode"`
	PayTypeCode       string      `json:"payTypeCode"`
	TransactionType   string      `json:"transactionType"`
	BalanceType       string      `json:"balanceType, optional"`
	BeforeBalance     float64     `json:"beforeBalance"`
	TransferAmount    float64     `json:"transferAmount"`
	AfterBalance      float64     `json:"afterBalance"`
	Comment           string      `json:"comment"`
	CreatedBy         string      `json:"createdBy"`
	CreatedAt         string      `json:"createdAt"`
	PayTypeData       PayType     `json:"payTypeData, optional" gorm:"foreignKey:Code;references:PayTypeCode"`
	ChannelData       ChannelData `json:"channelData, optional" gorm:"foreignKey:Code;references:ChannelCode"`
}

type MerchantPtBalanceRecord struct {
	ID                  int64       `json:"id, optional"`
	MerchantPtBalanceId int64       `json:"merchantPtBalanceId"`
	MerchantCode        string      `json:"merchantCode, optional"`
	CurrencyCode        string      `json:"currencyCode, optional"`
	OrderNo             string      `json:"orderNo"`
	OrderType           string      `json:"orderType, optional"`
	MerchantOrderNo     string      `json:"merchantOrderNo"`
	ChannelCode         string      `json:"channelCode"`
	PayTypeCode         string      `json:"payTypeCode"`
	TransactionType     string      `json:"transactionType"`
	BeforeBalance       float64     `json:"beforeBalance"`
	TransferAmount      float64     `json:"transferAmount"`
	AfterBalance        float64     `json:"afterBalance"`
	Comment             string      `json:"comment"`
	CreatedBy           string      `json:"createdBy"`
	CreatedAt           string      `json:"createdAt"`
	PayTypeData         PayType     `json:"payTypeData, optional" gorm:"foreignKey:Code;references:PayTypeCode"`
	ChannelData         ChannelData `json:"channelData, optional" gorm:"foreignKey:Code;references:ChannelCode"`
}

type MerchantCommissionRecord struct {
	ID                      int64   `json:"id, optional"`
	MerchantBalanceId       int64   `json:"merchantBalanceId"`
	MerchantCode            string  `json:"merchantCode, optional"`
	OrderNo                 string  `json:"orderNo, optional"`
	CurrencyCode            string  `json:"currencyCode, optional"`
	CommissionMonthReportId int64   `json:"commissionMonthReportId"`
	TransactionType         string  `json:"transactionType"`
	BeforeCommission        float64 `json:"before_commission"`
	TransferAmount          float64 `json:"transferAmount"`
	AfterCommission         float64 `json:"after_commission"`
	Comment                 string  `json:"comment"`
	CreatedBy               string  `json:"createdBy"`
	CreatedAt               string  `json:"createdAt"`
}

type MerchantBalanceRecordQueryAllRequest struct {
	MerchantBalanceId int64  `json:"merchantBalanceId, optional"`
	MerchantCode      string `json:"merchantCode, optional"`
	CurrencyCode      string `json:"currencyCode, optional"`
	OrderNo           string `json:"orderNo, optional"`
	OrderType         string `json:"orderType, optional"`
	TransactionType   string `json:"transactionType, optional"`
	BalanceType       string `json:"balanceType, optional"`
	PayTypeCode       string `json:"payTypeCode, optional"`
	StartAt           string `json:"startAt"`
	EndAt             string `json:"endAt"`
	PageNum           int    `json:"pageNum, optional" gorm:"-"`
	PageSize          int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantBalanceRecordQueryAllResponse struct {
	List     []MerchantBalanceRecord `json:"list"`
	PageNum  int                     `json:"pageNum"`
	PageSize int                     `json:"pageSize"`
	RowCount int64                   `json:"rowCount"`
}

type MerchantFrozenRecord struct {
	ID                int64   `json:"id, optional"`
	MerchantBalanceId int64   `json:"merchantBalanceId"`
	MerchantCode      string  `json:"merchantCode, optional"`
	CurrencyCode      string  `json:"currencyCode, optional"`
	OrderNo           string  `json:"orderNo"`
	OrderType         string  `json:"orderType"`
	TransactionType   string  `json:"transactionType"`
	BeforeFrozen      float64 `json:"beforeFrozen"`
	FrozenAmount      float64 `json:"frozenAmount"`
	AfterFrozen       float64 `json:"afterFrozen"`
	Comment           string  `json:"comment"`
	CreatedBy         string  `json:"createdBy"`
}

type MerchantFrozenRecordQueryAllRequest struct {
	MerchantBalanceId int64  `json:"merchantBalanceId, optional"`
	MerchantCode      string `json:"merchantCode, optional"`
	CurrencyCode      string `json:"currencyCode, optional"`
	OrderNo           string `json:"orderNo, optional"`
	OrderType         string `json:"orderType, optional"`
	TransactionType   string `json:"transactionType, optional"`
	PageNum           int    `json:"pageNum, optional" gorm:"-"`
	PageSize          int    `json:"pageSize, optional" gorm:"-"`
}

type MerchantFrozenRecordQueryAllResponse struct {
	List     []MerchantFrozenRecord `json:"list"`
	PageNum  int                    `json:"pageNum"`
	PageSize int                    `json:"pageSize"`
	RowCount int64                  `json:"rowCount"`
}

type Order struct {
	ID                      int64   `json:"id"`
	Type                    string  `json:"type"` //收支方式  (代付 DF 支付 ZF 下發 XF 內充 NC)
	MerchantCode            string  `json:"merchantCode"`
	TransAt                 string  `json:"transAt"`
	OrderNo                 string  `json:"orderNo"`
	BalanceType             string  `json:"balanceType"`
	BeforeBalance           float64 `json:"beforeBalance"`
	TransferAmount          float64 `json:"transferAmount"`
	Balance                 float64 `json:"balance"`
	FrozenAmount            float64 `json:"frozenAmount"`
	Status                  string  `json:"status"`          //訂單狀態(0:待處理 1:處理中 20:成功 30:失敗 31:凍結)
	RepaymentStatus         string  `json:"repaymentDtatus"` //还款状态：(0：不需还款、1:待还款、2：还款成功、3：还款失败)
	IsLock                  string  `json:"isLock"`
	IsTest                  string  `json:"isTest"`
	Memo                    string  `json:"memo"`
	ErrorType               string  `json:"errorType, optional"`
	ErrorNote               string  `json:"errorNote, optional"`
	ChannelCode             string  `json:"channelCode"`
	ChannelPayTypesCode     string  `json:"channelPayTypesCode"`
	PayTypeCode             string  `json:"payTypeCode"`
	Fee                     float64 `json:"fee"`
	HandlingFee             float64 `json:"handlingFee"`
	InternalChargeOrderPath string  `json:"internalChargeOrderPath"`
	CurrencyCode            string  `json:"currencyCode"`
	MerchantBankAccount     string  `json:"merchantBankAccount"`  //商戶銀行帳號
	MerchantBankNo          string  `json:"merchantBankNo"`       //商戶銀行代碼
	MerchantBankName        string  `json:"merchantBankName"`     //商戶姓名
	MerchantBankProvince    string  `json:"merchantBankProvince"` //商戶開戶縣市名
	MerchantBankCity        string  `json:"merchantBankCity"`     //商戶開戶縣市名
	MerchantAccountName     string  `json:"merchantAccountName"`  //開戶行名(代付、下發)
	ChannelBankAccount      string  `json:"channelBankAccount"`   //渠道銀行帳號
	ChannelBankNo           string  `json:"channelBankNo"`        //渠道銀行代碼
	ChannelBankName         string  `json:"channelBankName"`      //渠道银行名称
	ChannelAccountName      string  `json:"channelAccountName"`   //渠道账户姓名
	OrderAmount             float64 `json:"orderAmount"`          //订单金额
	ActualAmount            float64 `json:"actualAmount"`         //实际金额
	TransferHandlingFee     float64 `json:"transferHandlingFee"`
	MerchantOrderNo         string  `json:"merchantOrderNo"`     //商戶訂單編號
	ChannelOrderNo          string  `json:"channelOrderNo"`      //渠道订单编号
	Source                  string  `json:"source"`              //1:平台 2:API
	SourceOrderNo           string  `json:"sourceOrderNo"`       //來源訂單編號(From NC)
	ReasonType              string  `json:"reasonType"`          //原因類型(1=(補單)修改金額/2=(補單)重複支付/3=(補單)其它/11=追回)
	IsCalculateProfit       string  `json:"is_calculate_profit"` //已記算傭金利潤(0=否,1=是)
	CallBackStatus          string  `json:"callBackStatus, optional"`
	NotifyUrl               string  `json:"notifyUrl, optional"`
	PageUrl                 string  `json:"pageUrl, optional"`
	PersonProcessStatus     string  `json:"personProcessStatus, optional"` //人工处理状态：(0:待處理1:處理中2:成功3:失敗 10:不需处理)
	IsMerchantCallback      string  `json:"isMerchantCallback, optional"`  //是否已经回调商户(0：否、1:是、2:不需回调)(透过API需提供的资讯)
	CreatedBy               string  `json:"createdBy, optional"`
	UpdatedBy               string  `json:"updatedBy, optional"`
	ReviewedBy              string  `json:"reviewedBy, optional"`
	ChangeType              string  `json:"change_type, optional"`
	IsUsdt                  string  `json:"is_usdt, optional"`
	DefaultHandlingFee      float64 `json:"default_handling_fee, optional"`
}

type InternalChargeOrder struct {
	ID                      int64  `json:"id"`
	MerchantCode            string `json:"merchantCode"`
	OrderNo                 string `json:"orderNo"`
	MerchantAccountName     string `json:"merchantAccountName"`
	ChannelAccountName      string `json:"channelAccountName"`
	CurrencyCode            string `json:"currencyCode"`
	OrderAmount             string `json:"OrderAmount"`
	CreatedAt               string `json:"createdAt"`
	InternalChargeOrderPath string `json:"internalChargeOrderPath"`
	MerchantBankAccount     string `json:"merchantBankAccount"`
	ChannelBankAccount      string `json:"channelBankAccount"`
}

type WithDrawOrder struct {
	ID                   int64   `json:"id"`
	MerchantCode         string  `json:"merchantCode"`
	OrderNo              string  `json:"orderNo"`
	MerchantAccountName  string  `json:"accountName"`
	MerchantBankAccount  string  `json:"merchantBankAccount"`
	MerchantBankProvince string  `json:"merchantBankProvince"`
	MerchantBankCity     string  `json:"merchantBankCity"`
	CurrencyCode         string  `json:"currencyCode"`
	OrderAmount          string  `json:"OrderAmount"`
	CreatedAt            string  `json:"createdAt"`
	HandlingFee          float64 `json:"handlingfee"`
	Status               string  `json:"status"`
}

type BatchCheck struct {
	CurrencyCode         string  `json:"currencyCode"`
	MerchantAccountName  string  `json:"merchantAccountName"`
	MerchantBankAccount  string  `json:"merchantBankAccount"`
	MerchantBankNo       string  `json:"merchantBankNo"`
	MerchantBankName     string  `json:"merchantBankName"`
	MerchantBankProvince string  `json:"merchantBankProvince"`
	MerchantBankCity     string  `json:"merchantBankCity"`
	TransferAmount       float64 `json:"transferAmount, optional"`
	OrderAmount          float64 `json:"orderAmount, optional"`
	Valid                bool    `json:"valid, optional"`
	MinWithdrawCharge    float64 `json:"minWithdrawCharge, optional"`
	MaxWithdrawCharge    float64 `json:"maxWithdrawCharge, optional"`
}

type UploadImageRequest struct {
}

type ChannelWithdraw struct {
	ChannelCode    string  `json:"channelCode"`
	WithdrawAmount float64 `json:"withdrawAmount"`
}

type OrderChannels struct {
	ID                  int64       `json:"id"`
	OrderNo             string      `json:"orderNo"`
	ChannelCode         string      `json:"channelCode"`
	ChannelData         ChannelData `json:"channelData, optional" gorm:"foreignKey:Code;references:ChannelCode"`
	OrderAmount         float64     `json:"orderAmount"`
	TransferHandlingFee float64     `json:"transferHandlingFee"`
	HandlingFee         float64     `json:"handlingFee"`
}

type OrderInternalCreateRequest struct {
	Type                 string  `json:"type, optional"`
	MerchantBankAccount  string  `json:"merchantBankAccount"`
	MerchantAccountName  string  `json:"merchantAccountName"`
	MerchantBankNo       string  `json:"merchantBankNo"`
	MerchantBankName     string  `json:"merchantBankName, optional"`
	MerchantBankProvince string  `json:"merchantBankProvince, optional"`
	MerchantBankCity     string  `json:"merchantBankCity, optional"`
	ChannelBankAccount   string  `json:"channelBankAccount, optional"`
	ChannelAccountName   string  `json:"channelAccountName, optional"`
	ChannelBankNo        string  `json:"channelBankNo, optional"`
	CurrencyCode         string  `json:"currencyCode, optional"`
	OrderAmount          float64 `json:"orderAmount"`
}

type OrderProxyCreateRequeset struct {
	Index                string  `json:"index"`
	MerchantBankAccount  string  `json:"merchantBankAccount"`
	MerchantBankNo       string  `json:"merchantBankNo"`
	MerchantBankName     string  `json:"merchantBankName, optional"`
	MerchantAccountName  string  `json:"merchantAccountName"`
	MerchantBankProvince string  `json:"merchantBankProvince, optional"`
	MerchantBankCity     string  `json:"merchantBankCity, optional"`
	CurrencyCode         string  `json:"currencyCode"`
	OrderAmount          float64 `json:"orderAmount"`
}

type OrderWithdrawCreateRequest struct {
	MerchantAccountName  string  `json:"merchantAccountName"`
	MerchantBankAccount  string  `json:"merchantBankAccount"`
	MerchantBankNo       string  `json:"merchantBankNo"`
	MerchantBankName     string  `json:"merchantBankName, optional"`
	MerchantBankProvince string  `json:"merchantBankProvince, optional"`
	MerchantBankCity     string  `json:"merchantBankCity, optional"`
	CurrencyCode         string  `json:"currencyCode, optional"`
	OrderAmount          float64 `json:"orderAmount"`
	Index                string  `json:"index, optional"`
}

type MultipleOrderProxyCreateRequest struct {
	List []OrderProxyCreateRequeset `json:"list"`
}

type MultipleOrderWithdrawCreateRequest struct {
	List []OrderWithdrawCreateRequest `json:"list"`
}

type MultipleOrderCreateResponse struct {
	Index []string `json:"index"`
	Errs  []string `json:"errs"`
}

type OrderUpdateRequest struct {
	ID      int64  `json:"id"`
	Status  string `json:"status"`
	OrderNo string `json:"orderNo"`
	Memo    string `json:"memo, optional"`
}

type WithdrawOrderUpdateRequest struct {
	List []ChannelWithdraw `json:"list"`
	OrderUpdateRequest
}

type InternalChargeOrderQueryAllRequest struct {
	MerchantCode string `json:"merchantCode"`
	Status       string `json:"status"`
	StartAt      string `json:"startAt"`
	EndAt        string `json:"endAt"`
	PageNum      int    `json:"pageNum" gorm:"-"`
	PageSize     int    `json:"pageSize" gorm:"-"`
}

type InternalChargeOrderQueryAllResponse struct {
	List     []InternalChargeOrder `json:"list"`
	PageNum  int                   `json:"pageNum" gorm:"-"`
	PageSize int                   `json:"pageSize" gorm:"-"`
	RowCount int64                 `json:"rowCount"`
}

type WithDrawOrderQueryAllRequest struct {
	MerchantCode string `json:"merchantCode"`
	Status       string `json:"status"`
	StartAt      string `json:"startAt"`
	EndAt        string `json:"endAt"`
	PageNum      int    `json:"pageNum" gorm:"-"`
	PageSize     int    `json:"pageSize" gorm:"-"`
}

type WithdrawOrderQueryAllResponse struct {
	List     []WithDrawOrder `json:"list"`
	PageNum  int             `json:"pageNum" gorm:"-"`
	PageSize int             `json:"pageSize" gorm:"-"`
	RowCount int64           `json:"rowCount"`
}

type BatchCheckOrderRequest struct {
	List []BatchCheck `json:"list"`
	Type string       `json:"type"`
}

type BatchCheckOrderRespsonse struct {
	List        []BatchCheck `json:"list"`
	TotalPrice  float64      `json:"totalPrice"`
	HandlingFee float64      `json:"handlingFee"`
}

type OrderQueryWaitAuditNumberRequest struct {
	Type    string `json:"type"`
	StartAt string `json:"startAt"`
	EndAt   string `json:"endAt"`
}

type OrderQueryWaitAuditNumberResponse struct {
	WaitAuditNumber int64 `json:"waitAuditNumber"`
}

type OrderQueryMerchantChannelFeeRequest struct {
	CurrencyCode string `json:"currencyCode"`
	Type         string `json:"type"`
}

type OrderQueryMerchantCurrencyAndBanksResponse struct {
}

type WithdrawOrderChannelRequest struct {
	CurrencyCode string `json:"currencyCode"`
}

type WithdrawOrderChannelResponse struct {
	List []ChannelCodeAndHandlingFee `json:"list"`
}

type WithdrawOrderFeeRequest struct {
	CurrencyCode string `json:"currencyCode"`
	UserAccount  string `json:"userAccount"`
}

type WithdrawOrderFeeResponse struct {
	HandlerFee        float64 `json:"handlerFee"`
	MinWithdrawCharge float64 `json:"minWithdrawCharge"`
	MaxWithdrawCharge float64 `json:"maxWithdrawCharge"`
	Balance           float64 `json:"balance"`
}

type WithdrawOrderUpdateReviewProcssRequest struct {
	OrderNo string `json:"orderNo"`
}

type WithdrawVerifyWayResponse struct {
	PayingValidatedType string `json:"payingValidatedType"`
}

type WithdrawVerifyPasswordRequest struct {
	WithdrawPassword string `json:"withdrawPassword"`
}

type WithdrawVerifyPasswordResponse struct {
}

type OrderAction struct {
	ID          int64  `json:"id"`
	OrderNo     string `json:"orderNo"`
	Action      string `json:"action"`
	UserAccount string `json:"userAccount"`
	Comment     string `json:"comment"`
	CreatedAt   string `json:"createdAt"`
}

type OrderActionQueryAllRequest struct {
	OrderNo     string `json:"orderNo, optional"`
	UserAccount string `json:"userAccount, optional"`
	StartAt     string `json:"startAt, optional"`
	EndAt       string `json:"endAt, optional"`
	PageNum     int    `json:"pageNum, optional" gorm:"-"`
	PageSize    int    `json:"pageSize, optional" gorm:"-"`
}

type OrderActionQueryAllResponse struct {
	List     []OrderAction `json:"list"`
	PageNum  int           `json:"pageNum" gorm:"-"`
	PageSize int           `json:"pageSize" gorm:"-"`
	RowCount int64         `json:"rowCount"`
}

type ReceiptRecord struct {
	ID                  int64       `json:"id"`
	MerchantCode        string      `json:"merchantCode"`
	OrderNo             string      `json:"orderNo"`
	MerchantOrderNo     string      `json:"merchantOrderNo"`
	CurrencyCode        string      `json:"currencyCode"`
	ChannelPayTypesCode string      `json:"channelPayTypesCode"`
	ChannelCode         string      `json:"channelCode"`
	Type                string      `json:"type"`
	PayTypeCode         string      `json:"payTypeCode"`
	OrderAmount         float64     `json:"orderAmount"`
	TransferAmount      float64     `json:"transferAmount"`
	TransferHandlingFee float64     `json:"transferHandlingFee"`
	HandlingFee         float64     `json:"handlingFee"`
	Fee                 float64     `json:"fee"`
	BeforeBalance       float64     `json:"beforeBalance"`
	Balance             float64     `json:"balance"`
	Status              string      `json:"status"`
	Memo                string      `json:"memo"`
	PayTypeData         PayType     `json:"payTypeData, optional" gorm:"foreignKey:Code;references:PayTypeCode"`
	ChannelData         ChannelData `json:"channelData, optional" gorm:"foreignKey:Code;references:ChannelCode"`
	TransAt             string      `json:"transAt"`
	CreatedAt           string      `json:"createdAt"`
}

type DeductRecord struct {
	ID                  int64           `json:"id"`
	MerchantCode        string          `json:"merchantCode"`
	OrderNo             string          `json:"orderNo"`
	MerchantOrderNo     string          `json:"merchantOrderNo"`
	CurrencyCode        string          `json:"currencyCode"`
	Type                string          `json:"type"`
	OrderChannels       []OrderChannels `json:"orderChannels, optional" gorm:"foreignKey:OrderNo;references:OrderNo"`
	OrderAmount         float64         `json:"orderAmount"`
	TransferAmount      float64         `json:"transferAmount"`
	TransferHandlingFee float64         `json:"transferHandlingFee"`
	HandlingFee         float64         `json:"handlingFee"`
	Fee                 float64         `json:"fee"`
	BeforeBalance       float64         `json:"beforeBalance"`
	Balance             float64         `json:"balance"`
	Status              string          `json:"status"`
	Memo                string          `json:"memo"`
	CreatedAt           string          `json:"createdAt"`
}

type PersonalRepayment struct {
	ID                    int64  `json:"id"`
	OrderNo               string `json:"orderNo"`
	MerchantOrderNo       string `json:"merchantOrderNo"`
	ChannelCode           string `json:"channelCode"`
	MerchantBankAccount   string `json:"merchantBankAccount"`
	MerchantAccountName   string `json:"merchantAccountName"`
	MerchantBankNo        string `json:"merchantBankNo"`
	MerchantBankProvince  string `json:"merchantBankProvince"`
	MerchantBankCity      string `json:"merchantBankCity"`
	Source                string `json:"source"`
	CreatedAt             string `json:"createdAt"`
	TransAt               string `json:"transAt"`
	PersonalProcessStatus string `json:"personalProcessStatus"`
}

type FrozenRecord struct {
	ID                  int64       `json:"id"`
	MerchantCode        string      `json:"merchantCode"`
	OrderNo             string      `json:"orderNo"`
	MerchantOrderNo     string      `json:"merchantOrderNo"`
	CurrencyCode        string      `json:"currencyCode"`
	ChannelPayTypesCode string      `json:"channelPayTypesCode"`
	ChannelCode         string      `json:"channelCode"`
	Type                string      `json:"type"`
	PayTypeCode         string      `json:"payTypeCode"`
	PayTypeCodeNum      string      `json:"payTypeCodeNum"`
	FrozenAmount        float64     `json:"frozenAmount"`
	Status              string      `json:"status"`
	Memo                string      `json:"memo"`
	PayTypeData         PayType     `json:"payTypeData, optional" gorm:"foreignKey:Code;references:PayTypeCode"`
	ChannelData         ChannelData `json:"channelData, optional" gorm:"foreignKey:Code;references:ChannelCode"`
	TransAt             string      `json:"transAt"`
	CreatedAt           string      `json:"createdAt"`
	UpdatedAt           string      `json:"updatedAt"`
	UpdatedBy           string      `json:"updatedBy"`
}

type ReversalRecordRequest struct {
	OrderNo string `json:"orderNo"`
	Comment string `json:"comment, optional"`
}

type ReceiptRecordQueryAllRequest struct {
	MerchantCode    string `json:"merchantCode, optional"`
	OrderNo         string `json:"orderNo, optional"`
	MerchantOrderNo string `json:"merchantOrderNo, optional"`
	DateType        string `json:"dateType, optional"`
	StartAt         string `json:"startAt, optional"`
	EndAt           string `json:"endAt, optional"`
	Status          string `json:"status, optional"`
	Type            string `json:"type, optional"`
	PayTypeCode     string `json:"payTypeCode, optional"`
	CurrencyCode    string `json:"currencyCode, optional"`
	PageNum         int    `json:"pageNum, optional" gorm:"-"`
	PageSize        int    `json:"pageSize, optional" gorm:"-"`
}

type ReceiptRecordQueryAllResponse struct {
	List     []ReceiptRecord `json:"list"`
	PageNum  int             `json:"pageNum" gorm:"-"`
	PageSize int             `json:"pageSize" gorm:"-"`
	RowCount int64           `json:"rowCount"`
}

type FrozenReceiptOrderRequest struct {
	OrderNo      string  `json:"orderNo"`
	FrozenAmount float64 `json:"frozenAmount"`
	Comment      string  `json:"comment, optional"`
}

type UnfrozenOrderRequest struct {
	OrderNo string `json:"orderNo"`
}

type MakeUpReceiptOrderRequest struct {
	OrderNo        string  `json:"orderNo"`
	ChannelOrderNo string  `json:"channelOrderNo"`
	Amount         float64 `json:"amount"`
}

type DeductRecordQueryAllRequest struct {
	MerchantCode    string `json:"merchantCode, optional"`
	OrderNo         string `json:"orderNo, optional"`
	MerchantOrderNo string `json:"merchantOrderNo, optional"`
	DateType        string `json:"dateType, optional"`
	StartAt         string `json:"startAt, optional"`
	EndAt           string `json:"endAt, optional"`
	Status          string `json:"status, optional"`
	Type            string `json:"type, optional"`
	ChannelCode     string `json:"channelCode, optional"`
	CurrencyCode    string `json:"currencyCode, optional"`
	Source          string `json:"source, optional"`
	PageNum         int    `json:"pageNum, optional" gorm:"-"`
	PageSize        int    `json:"pageSize, optional" gorm:"-"`
}

type DeductRecordQueryAllResponse struct {
	List     []DeductRecord `json:"list"`
	PageNum  int            `json:"pageNum" gorm:"-"`
	PageSize int            `json:"pageSize" gorm:"-"`
	RowCount int64          `json:"rowCount"`
}

type PersonalRepaymentRequest struct {
	OrderNo      string `json:"orderNo, optional"`
	ChannelCode  string `json:"channelCode, optional"`
	Source       string `json:"source"`
	StartAt      string `json:"startAt"`
	EndAt        string `json:"endAt"`
	CurrencyCode string `json:"currencyCode"`
	PageNum      int    `json:"pageNum, optional" gorm:"-"`
	PageSize     int    `json:"pageSize, optional" gorm:"-"`
}

type PersonalRepaymentResponse struct {
	List     []PersonalRepayment `json:"list"`
	PageNum  int                 `json:"pageNum" gorm:"-"`
	PageSize int                 `json:"pageSize" gorm:"-"`
	RowCount int64               `json:"rowCount"`
}

type FrozenRecordQueryAllRequest struct {
	MerchantCode    string `json:"merchantCode, optional"`
	OrderNo         string `json:"orderNo, optional"`
	MerchantOrderNo string `json:"merchantOrderNo, optional"`
	StartAt         string `json:"startAt, optional"`
	EndAt           string `json:"endAt, optional"`
	Type            string `json:"type, optional"`
	PayTypeCode     string `json:"payTypeCode, optional"`
	ChannelCode     string `json:"channelCode, optional"`
	CurrencyCode    string `json:"currencyCode, optional"`
	Source          string `json:"source, optional"`
	PageNum         int    `json:"pageNum, optional" gorm:"-"`
	PageSize        int    `json:"pageSize, optional" gorm:"-"`
}

type FrozenRecordQueryAllResponse struct {
	List     []FrozenRecord `json:"list"`
	PageNum  int            `json:"pageNum" gorm:"-"`
	PageSize int            `json:"pageSize" gorm:"-"`
	RowCount int64          `json:"rowCount"`
}

type OrderChannelRecordReqeust struct {
	OrderNo string `json:"orderNo"`
}

type OrderChannelRecordResponse struct {
	List []OrderChannels `json:"list"`
}

type PersonalStatusUpdateResponse struct {
	OrderNo             string `json:"orderNo"`
	PersonProcessStatus string `json:"personProcessStatus"`
	Comment             string `json:"comment, optional"`
	ChannelOrderNo      string `json:"channelOrderNo, optional"`
	ChannelTransAt      string `json:"channelTransAt, optional"`
}

type OrderFeeProfit struct {
	ID                  int64   `json:"id"`
	OrderNo             string  `json:"orderNo"`
	MerchantCode        string  `json:"merchantCode"`
	AgentLayerNo        string  `json:"agentLayerNo"`
	AgentParentCode     string  `json:"agentParentCode"`
	BalanceType         string  `json:"balanceType"`
	Fee                 float64 `json:"fee"`
	HandlingFee         float64 `json:"handlingFee"`
	TransferHandlingFee float64 `json:"transferHandlingFee"`
	ProfitAmount        float64 `json:"profitAmount"`
}

type OrderFeeProfitQueryAllRequest struct {
	OrderNo         string `json:"orderNo"`
	MerchantCode    string `json:"merchantCode"`
	AgentLayerNo    string `json:"agentLayerNo"`
	AgentParentCode string `json:"agentParentCode"`
	PageNum         int    `json:"pageNum, optional" gorm:"-"`
	PageSize        int    `json:"pageSize, optional" gorm:"-"`
}

type OrderFeeProfitQueryAllResponse struct {
	List     []OrderFeeProfit `json:"list"`
	PageNum  int              `json:"pageNum" gorm:"-"`
	PageSize int              `json:"pageSize" gorm:"-"`
	RowCount int64            `json:"rowCount"`
}

type RespData struct {
	WithdrawOrderNo string `json:"withdrawOrderNo"`
	Sign            string `json:"sign"`
}

type WithdrawApiOrderRequest struct {
	MerchantId   string `json:"merchantId"`
	Sign         string `json:"sign"`
	NotifyUrl    string `json:"notifyUrl"`
	PageUrl      string `json:"pageUrl, optional"`
	WithdrawName string `json:"withdrawName"`
	BankName     string `json:"bankName"`
	AccountNo    string `json:"accountNo"`
	BankProvince string `json:"bankProvince, optional"`
	BankCity     string `json:"bankCity, optional"`
	OrderAmount  string `json:"orderAmount"`
	Language     string `json:"language"`
	OrderNo      string `json:"orderNo"`
	Currency     string `json:"currency"`
}

type WithdrawApiOrderResponse struct {
	RespCode string   `json:"respCode"`
	RespMsg  string   `json:"respMsg"`
	RespData RespData `json:"data"`
	Trace    string   `json:"trace"`
}

type WithdrawApiQueryRequest struct {
	MerchantId string `json:"merchantId"`
	OrderNo    string `json:"orderNo"`
	Sign       string `json:"sign"`
}

type WithdrawApiQueryResponse struct {
	RespCode    string `json:"respCode"`
	RespMsg     string `json:"respMsg"`
	OrderStatus string `json:"orderStatus"`
	MerchantId  string `json:"merchantId"`
	OrderAmount string `json:"orderAmount"`
	Sign        string `json:"sign"`
}

type PayOrderRequest struct {
	AccessType    string `json:"accessType" validate:"max=2"`
	MerchantId    string `json:"merchantId"`
	NotifyUrl     string `json:"notifyUrl"  validate:"max=180"`
	PageUrl       string `json:"pageUrl, optional"`
	Language      string `json:"language" validate:"max=8"`
	Sign          string `json:"sign"`
	JumpType      string `json:"jumpType, optional" validate:"max=12"`
	LoginType     string `json:"loginType, optional" validate:"max=12"`
	OrderNo       string `json:"orderNo" validate:"max=40"`
	OrderAmount   string `json:"orderAmount"`
	Currency      string `json:"currency" validate:"max=5"`
	PayType       string `json:"payType" validate:"max=8"`
	OrderTime     string `json:"orderTime, optional" validate:"max=20"`
	OrderName     string `json:"orderName" validate:"max=180"`
	BankCode      string `json:"bankCode, optional" validate:"max=12"`
	Phone         string `json:"phone, optional" validate:"max=18"`
	PayTypeNo     string `json:"payTypeNo, optional" validate:"max=4"`
	UserId        string `json:"userId, optional" validate:"max=255"`
	MerchantLevel string `json:"merchantLevel, optional" validate:"max=3"`
	UserIp        string `json:"userIp, optional" validate:"max=64"`
}

type PayOrderResponse struct {
	BankCode   string `json:"bankCode"`
	Info       string `json:"info"`
	PayOrderNo string `json:"payOrderNo"`
	RespCode   string `json:"respCode"`
	RespMsg    string `json:"respMsg"`
	Sign       string `json:"sign"`
	Status     int64  `json:"status"`
	Type       string `json:"type"`
}

type PayQueryRequest struct {
	AccessType string `json:"accessType"`
	MerchantId string `json:"merchantId"`
	Sign       string `json:"sign"`
	Language   string `json:"language, optional"`
	OrderNo    string `json:"orderNo"`
	PayTypeNo  string `json:"payTypeNo, optional"`
}

type PayQueryResponse struct {
	RespCode     string `json:"respCode"`
	RespMsg      string `json:"respMsg"`
	Language     string `json:"language"`
	BankCode     string `json:"bankCode"`
	Fee          string `json:"fee"`
	MerchantId   string `json:"merchantId"`
	OrderAmount  string `json:"orderAmount"`
	OrderNo      string `json:"orderNo"`
	OrderTime    string `json:"orderTime"`
	PayOrderId   string `json:"payOrderId"`
	PayOrderTime string `json:"payOrderTime"`
	OrderStatus  string `json:"orderStatus"`
	Sign         string `json:"sign"`
}

type PayQueryBalanceRequest struct {
	AccessType string `json:"accessType"`
	MerchantId string `json:"merchantId"`
	Sign       string `json:"sign"`
	Currency   string `json:"currency, optional" validate:"max=5"`
}

type PayQueryBalanceResponse struct {
	RespCode        string `json:"respCode"`
	RespMsg         string `json:"respMsg"`
	PayAmount       string `json:"payAmount"`
	ProxyAmount     string `json:"proxyAmount"`
	AvailableAmount string `json:"availableAmount"`
	FrozenAmount    string `json:"frozenAmount"`
	Sign            string `json:"sign"`
}

type PayCallBackRequest struct {
	CallbackTime   string  `json:"callbackTime"`
	ChannelOrderNo string  `json:"channelOrderNo"`
	OrderAmount    float64 `json:"orderAmount"`
	OrderStatus    string  `json:"orderStatus"`
	PayOrderNo     string  `json:"payOrderNo"`
	Sign           string  `json:"sign"`
}

type PayCallBackResponse struct {
	RespCode string `json:"respCode"`
	RespMsg  string `json:"respMsg"`
	Status   int64  `json:"status"`
	Data     int64  `json:"data"`
}

type ProxyPayOrderRequest struct {
	AccessType   string  `json:"accessType" validate:"max=2"`
	MerchantId   string  `json:"merchantId" valiate: "required"`
	Sign         string  `json:"sign" valiate: "required"`
	NotifyUrl    string  `json:"notifyUrl" validate: "required"`
	Language     string  `json:"language" valiate: "required"`
	OrderNo      string  `json:"orderNo" validate: "required"`
	BankId       string  `json:"bankId" validate: "required"`
	BankName     string  `json:"bankName" validate: "required"`
	BankProvince string  `json:"bankProvince" validate: "required"`
	BankCity     string  `json:"bankCity" validate: "required"`
	BranchName   string  `json:"branchName, optional"`
	BankNo       string  `json:"bankNo" valiate: "required"`
	OrderAmount  float64 `json:"orderAmount" validate: "required"` //到小數兩位
	DefrayName   string  `json:"defrayName" validate: "required"`
	DefrayId     string  `json:"defrayId, optional"`
	DefrayMobile string  `json:"defrayMobile, optional"`
	DefrayEmail  string  `json:"defrayEmail, optional"`
	Currency     string  `json:"currency" validate: "required"`
	PayTypeSubNo string  `json:"payTypeSubNo,optional"`
}

type ProxyPayOrderResponse struct {
	RespCode    string `json:"respCode"`
	RespMsg     string `json:"respMsg"`
	MerchantId  string `json:"merchantId"`
	OrderNo     string `json:"orderNo"`
	PayOrderNo  string `json:"payOrderNo"`
	OrderStatus string `json:"orderStatus"`
	Sign        string `json:"sign"`
}

type ProxyPayOrderQueryRequest struct {
	AccessType string `json:"accessType" valiate: "required"`
	MerchantId string `json:"merchantId" valiate: "required"`
	OrderNo    string `json:"orderNo" valiate: "required"`
	Sign       string `json:"sign" valiate: "required"`
	Language   string `json:"language" valiate: "required"`
}

type ProxyPayOrderQueryResponse struct {
	RespCode       string `json:"respCode"`
	RespMsg        string `json:"respMsg"`
	MerchantId     string `json:"merchantId"`
	OrderNo        string `json:"orderNo"`
	LastUpdateTime string `json:"lastUpdateTime"`
	PayOrderNo     string `json:"payOrderNo"`
	OrderStatus    string `json:"orderStatus"`
	CallbackStatus string `json:"callbackStatus"`
	OrderAmount    string `json:"orderAmount"`
	Fee            string `json:"fee"`
	Sign           string `json:"sign"`
}

type ChannelData struct {
	ID                      int64            `json:"id, optional"`
	Code                    string           `json:"code, optional"`
	Name                    string           `json:"name, optional"`
	ProjectName             string           `json:"projectName, optional"`
	IsProxy                 string           `json:"isProxy, optional"`
	IsNzPre                 string           `json:"isNzPre, optional"`
	ApiUrl                  string           `json:"apiUrl, optional"`
	CurrencyCode            string           `json:"currencyCode, optional"`
	ChannelWithdrawCharge   float64          `json:"channelWithdrawCharge, optional"`
	Balance                 float64          `json:"balance, optional"`
	Status                  string           `json:"status, optional"`
	Device                  string           `json:"device,optional"`
	MerId                   string           `json:"merId, optional"`
	MerKey                  string           `json:"merKey, optional"`
	PayUrl                  string           `json:"payUrl, optional"`
	PayQueryUrl             string           `json:"payQueryUrl, optional"`
	PayQueryBalanceUrl      string           `json:"payQueryBalanceUrl, optional"`
	ProxyPayUrl             string           `json:"proxyPayUrl, optional"`
	ProxyPayQueryUrl        string           `json:"proxyPayQueryUrl, optional"`
	ProxyPayQueryBalanceUrl string           `json:"proxyPayQueryBalanceUrl, optional"`
	WhiteList               string           `json:"whiteList, optional"`
	PayTypeMapList          []PayTypeMap     `json:"payTypeMapList, optional" gorm:"-"`
	PayTypeMap              string           `json:"payTypeMap, optional"`
	ChannelPayTypeList      []ChannelPayType `json:"channelPayTypeList, optional" gorm:"foreignKey:ChannelCode;references:Code"`
	ChannelPort             string           `json:"channelPort, optional"`
	WithdrawBalance         float64          `json:"withdrawBalance, optional"`
	ProxypayBalance         float64          `json:"proxypayBalance, optional"`
	BankCodeMapList         []BankCodeMap    `json:"bankCodeMapList, optional" gorm:"-"`
	Banks                   []Bank           `json:"banks, optional" gorm:"many2many:ch_channel_banks;foreignKey:Code;joinForeignKey:channel_code;references:bank_no;joinReferences:bank_no"`
}

type ChannelDataCreateRequest struct {
	Code                    string           `json:"code, optional"`
	Name                    string           `json:"name" valiate: "required"`
	ProjectName             string           `json:"projectName, optional"`
	IsProxy                 string           `json:"isProxy" valiate: "required"`
	IsNZPre                 string           `json:"isNzPre" valiate: "required"`
	ApiUrl                  string           `json:"apiUrl, optional"`
	CurrencyCode            string           `json:"currencyCode" valiate: "required"`
	ChannelWithdrawCharge   float64          `json:"channelWithdrawCharge, optional"`
	Balance                 float64          `json:"balance, optional"`
	Status                  string           `json:"status, optional"`
	Device                  string           `json:"device,optional"`
	CreatedAt               string           `json:"createdAt, optional"`
	UpdatedAt               string           `json:"updatedAt, optional"`
	MerId                   string           `json:"merId, optional"`
	MerKey                  string           `json:"merKey , optional"`
	PayUrl                  string           `json:"payUrl, optional"`
	PayQueryUrl             string           `json:"payQueryUrl, optional"`
	PayQueryBalanceUrl      string           `json:"payQueryBalanceUrl, optional"`
	ProxyPayUrl             string           `json:"proxyPayUrl, optional"`
	ProxyPayQueryUrl        string           `json:"proxyPayQueryUrl, optional"`
	ProxyPayQueryBalanceUrl string           `json:"proxyPayQueryBalanceUrl, optional"`
	WhiteList               string           `json:"whiteList, optional"`
	PayTypeMapList          []PayTypeMap     `json:"payTypeMapList, optional" gorm:"-"`
	PayTypeMap              string           `json:"payTypeMap, optional"`
	ChannelPayTypeList      []ChannelPayType `json:"channelPayTypeList, optional" gorm:"foreignKey:ChannelCode;references:Code"`
	ChannelPort             string           `json:"channelPort, optional"`
	WithdrawBalance         float64          `json:"withdrawBalance, optional"`
	ProxypayBalance         float64          `json:"proxypayBalance, optional"`
	BankCodeMapList         []BankCodeMap    `json:"bankCodeMapList, optional" gorm:"-"`
	Banks                   []Bank           `json:"banks, optional" gorm:"many2many:ch_channel_banks;foreignKey:Code;joinForeignKey:channel_code;references:bank_no;joinReferences:bank_no"`
}

type BankCodeMap struct {
	ID          int64  `json:"id, optional"`
	ChannelCode string `json:"channelCode, optional"`
	BankNo      string `json:"bankNo"`
	MapCode     string `json:"mapCode"`
}

type PayTypeMap struct {
	ID      int64  `json:"id, optional"`
	PayType string `json:"payType"`
	TypeNo  string `json:"typeNo"`
	MapCode string `json:"mapCode"`
}

type ChannelDataUpdateRequest struct {
	ID                      int64            `json:"id, optional"`
	Code                    string           `json:"code" valiate: "required"`
	Name                    string           `json:"name" valiate: "required"`
	ProjectName             string           `json:"projectName" valiate: "required"`
	IsProxy                 string           `json:"isProxy" valiate: "required"`
	IsNZPre                 string           `json:"isNzPre" valiate: "required"`
	ApiUrl                  string           `json:"apiUrl, optional"`
	CurrencyCode            string           `json:"currencyCode, optional"`
	ChannelWithdrawCharge   float64          `json:"channelWithdrawCharge, optional"`
	Balance                 float64          `json:"balance, optional"`
	Status                  string           `json:"status, optional"`
	CreatedAt               string           `json:"createdAt, optional"`
	UpdatedAt               string           `json:"updatedAt, optional"`
	Device                  string           `json:"device,optional"`
	MerId                   string           `json:"merId, optional"`
	MerKey                  string           `json:"merKey , optional"`
	PayUrl                  string           `json:"payUrl, optional"`
	PayQueryUrl             string           `json:"payQueryUrl, optional"`
	PayQueryBalanceUrl      string           `json:"payQueryBalanceUrl, optional"`
	ProxyPayUrl             string           `json:"proxyPayUrl, optional"`
	ProxyPayQueryUrl        string           `json:"proxyPayQueryUrl, optional"`
	ProxyPayQueryBalanceUrl string           `json:"proxyPayQueryBalanceUrl, optional"`
	WhiteList               string           `json:"whiteList, optional"`
	PayTypeMapList          []PayTypeMap     `json:"payTypeMapList, optional" gorm:"-"`
	PayTypeMap              string           `json:"payTypeMap, optional"`
	ChannelPayTypeList      []ChannelPayType `json:"channelPayTypeList, optional" gorm:"foreignKey:ChannelCode;references:Code"`
	ChannelPort             string           `json:"channelPort, optional"`
	WithdrawBalance         float64          `json:"withdrawBalance, optional"`
	ProxypayBalance         float64          `json:"proxypayBalance, optional"`
	BankCodeMapList         []BankCodeMap    `json:"bankCodeMapList, optional" gorm:"-"`
	Banks                   []Bank           `json:"banks, optional" gorm:"many2many:ch_channel_banks;foreignKey:Code;joinForeignKey:channel_code;references:bank_no;joinReferences:bank_no"`
}

type ChannelDataDeleteRequest struct {
	ID   int64  `json:"id, optional"`
	Code string `json:"code",valiate: "required"`
}

type ChannelDataQueryRequest struct {
	ID   int64  `json:"id, optional"`
	Code string `json:"code",valiate: "required"`
}

type ChannelDataQueryResponse struct {
	ChannelData
}

type ChannelDataQueryAllRequest struct {
	Code         string `json:"code,optional"`
	Name         string `json:"name,optional"`
	CurrencyCode string `json:"currencyCode,optional"`
	Status       string `json:"status, optional"`
	IsProxy      string `json:"isProxy, optional"`
	Device       string `json:"device,optional"`
	PageNum      int    `json:"pageNum" gorm:"-"` //gorm:"-" 忽略這參數檢查是否有給
	PageSize     int    `json:"pageSize" gorm:"-"`
}

type ChannelDataQueryAllResponse struct {
	List     []ChannelData `json:"list"`
	PageNum  int           `json:"pageNum"`
	PageSize int           `json:"pageSize"`
	RowCount int64         `json:"rowCount"`
}

type ChannelDataGetDropDownListRequest struct {
	Code         string   `json:"code,optional"`
	Name         string   `json:"name,optional"`
	Status       []string `json:"status,optional"`
	CurrencyCode string   `json:"currencyCode,optional"`
}

type ChannelDataDropDownItem struct {
	Id   string `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type ChannelCodeAndHandlingFee struct {
	Code                  string `json:"channelCode"`
	ChannelWithdrawCharge string `json:"channelWithdrawCharge"`
	Name                  string `json:"name"`
}

type ChannelPayType struct {
	ID                int64   `json:"id, optional"`
	Code              string  `json:"code, optional"`
	ChannelCode       string  `json:"channelCode, optional"`
	PayTypeCode       string  `json:"payTypeCode, optional"`
	PayTypeCodeNum    string  `json:"payTypeCodeNum, optional"`
	Fee               float64 `json:"fee, optional"`
	HandlingFee       float64 `json:"handlingFee, optional"`
	MaxInternalCharge float64 `json:"maxInternalCharge, optional"`
	DailyTxLimit      float64 `json:"dailyTxLimit, optional"`
	SingleMinCharge   float64 `json:"singleMinCharge, optional"`
	SingleMaxCharge   float64 `json:"singleMaxCharge, optional"`
	FixedAmount       string  `json:"fixedAmount, optional"`
	BillDate          int64   `json:"billDate, optional"`
	Status            string  `json:"status, optional"`
	IsProxy           string  `json:"isProxy, optional"`
	Device            string  `json:"device, optional"`
	MapCode           string  `json:"mapCode, optional"`
}

type ChannelPayTypeCreateRequest struct {
	Code              string  `json:"code" valiate: "required"`
	ChannelCode       string  `json:"channelCode" valiate: "required"`
	PayTypeCode       string  `json:"payTypeCode" valiate: "required"`
	PayTypeCodeNum    string  `json:"payTypeCodeNum" valiate: "required"`
	Fee               float64 `json:"fee, optional"`
	HandlingFee       float64 `json:"handlingFee, optional"`
	MaxInternalCharge float64 `json:"maxInternalCharge, optional"`
	DailyTxLimit      float64 `json:"dailyTxLimit, optional"`
	SingleMinCharge   float64 `json:"singleMinCharge, optional"`
	SingleMaxCharge   float64 `json:"singleMaxCharge, optional"`
	FixedAmount       string  `json:"fixedAmount, optional"`
	BillDate          int64   `json:"billDate, optional"`
	Status            string  `json:"status" valiate: "required"`
	IsProxy           string  `json:"isProxy, optional"`
	Device            string  `json:"device, optional"`
	MapCode           string  `json:"mapCode, optional"`
}

type ChannelPayTypeUpdateRequest struct {
	ID                int64   `json:"id, optional"`
	Code              string  `json:"code" valiate: "required"`
	ChannelCode       string  `json:"channelCode" valiate: "required"`
	PayTypeCode       string  `json:"payTypeCode" valiate: "required"`
	PayTypeCodeNum    string  `json:"payTypeCodeNum" valiate: "required"`
	Fee               float64 `json:"fee, optional"`
	HandlingFee       float64 `json:"handlingFee, optional"`
	MaxInternalCharge float64 `json:"maxInternalCharge, optional"`
	DailyTxLimit      float64 `json:"dailyTxLimit, optional"`
	SingleMinCharge   float64 `json:"singleMinCharge, optional"`
	SingleMaxCharge   float64 `json:"singleMaxCharge, optional"`
	FixedAmount       string  `json:"fixedAmount, optional"`
	BillDate          int64   `json:"billDate, optional"`
	Status            string  `json:"status" valiate: "required"`
	IsProxy           string  `json:"isProxy, optional"`
	Device            string  `json:"device, optional"`
	MapCode           string  `json:"mapCode, optional"`
}

type ChannelPayTypeQueryAllRequest struct {
	ChannelName string `json:"channelName,optional"`
	PayTypeName string `json:"payTypeName,optional"`
	Status      string `json:"status,optional"`
	IsProxy     string `json:"isProxy,optional"`
	Currency    string `json:"currency,optional"`
	PageNum     int    `json:"pageNum" gorm:"-"` //gorm:"-" 忽略這參數檢查是否有給
	PageSize    int    `json:"pageSize" gorm:"-"`
}

type ChannelPayTypeQueryAllResponse struct {
	List     []ChannelPayTypeQueryResponse `json:"list"`
	PageNum  int                           `json:"pageNum"`
	PageSize int                           `json:"pageSize"`
	RowCount int64                         `json:"rowCount"`
}

type ChannelPayTypeQueryRequest struct {
	ID int64 `json:"id"`
}

type ChannelPayTypeQueryResponse struct {
	ChannelPayType
	CurrencyCode string `json:"currencyCode"`
	PayTypeName  string `json:"payTypeName"`
	ChannelName  string `json:"channelName"`
}

type ChannelPayTypeDeleteRequest struct {
	ID int64 `json:"id"`
}

type PayType struct {
	ID           int64         `json:"id, optional"`
	Code         string        `json:"code, optional"`
	Name         string        `json:"name, optional"`
	Currency     string        `json:"currency, optional"`
	ImgUrl       string        `json:"imgUrl, optional"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_pay_types:foreignKey:code;joinForeignKey:pay_type_code;references:code;joinReferences:channel_code"`
}

type PayTypeCreateRequest struct {
	Code         string        `json:"code, optional" valiate: "required"`
	Name         string        `json:"name, optional" valiate: "required"`
	Currency     string        `json:"currency, optional"`
	ImgUrl       string        `json:"imgUrl, optional"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_pay_types:foreignKey:code;joinForeignKey:pay_type_code;references:code;joinReferences:channel_code"`
}

type PayTypeUpdateRequest struct {
	ID           int64         `json:"id" valiate: "required"`
	Code         string        `json:"code, optional" valiate: "required"`
	Name         string        `json:"name, optional" valiate: "required"`
	Currency     string        `json:"currency, optional"`
	ImgUrl       string        `json:"imgUrl, optional"`
	ChannelDatas []ChannelData `json:"channelDatas, optional" gorm:"many2many:ch_channel_pay_types:foreignKey:code;joinForeignKey:pay_type_code;references:code;joinReferences:channel_code"`
}

type PayTypeDeleteRequest struct {
	ID int64 `json:"id"`
}

type PayTypeQueryRequest struct {
	ID int64 `json:"id"`
}

type PayTypeQueryResponse struct {
	PayType
}

type PayTypeQueryAllRequest struct {
	Code     string `json:"code,optional"`
	Name     string `json:"name,optional"`
	Currency string `json:"currency,optional"`
	PageNum  int    `json:"pageNum, optional" gorm:"-"` //gorm:"-" 忽略這參數檢查是否有給
	PageSize int    `json:"pageSize, optional" gorm:"-"`
}

type PayTypeQueryAllResponse struct {
	List     []PayType `json:"list"`
	PageNum  int       `json:"pageNum"`
	PageSize int       `json:"pageSize"`
	RowCount int64     `json:"rowCount"`
}

type ChannelBank struct {
	ID          int64  `json:"id, optional"`
	ChannelCode string `json:"channelCode, optional"`
	BankNo      string `json:"bankNo, optional"`
	MapCode     string `json:"mapCode, optional"`
}

type ChannelBankCreateRequest struct {
	ChannelCode string `json:"channelCode, optional"`
	BankNo      string `json:"bankNo" valiate: "required"`
	MapCode     string `json:"mapCode"`
}

type ChannelBankUpdateRequest struct {
	ID          int64  `json:"id, optional"`
	ChannelCode string `json:"channelCode" valiate: "required"`
	BankNo      string `json:"bankNo" valiate: "required"`
	MapCode     string `json:"mapCode"`
}

type ChannelBankDeleteRequest struct {
	ID int64 `json:"id"`
}

type ChannelBankQueryRequest struct {
	ID          int64  `json:"id"`
	ChannelCode string `json:"channelCode"`
	BankNo      string `json:"bankNo"`
}

type ChannelBankQueryResponse struct {
	ChannelBank ChannelBank `json:"channelBank"`
}

type ChannelBankQueryAllRequest struct {
	ID          int64  `json:"id"`
	ChannelCode string `json:"channelCode"`
	BankNo      string `json:"bankNo"`
}

type ChannelBankQueryAllResponse struct {
	ChannelBankList []ChannelBank `json:"channelBankList"`
}
